version: '3'
services:
  ssh-vpn:
    image: j0sch7/ssh-vpn
    container_name: ssh-vpn
    restart: unless-stopped
    command: -D 1337 -M 0 -C -p $SSH_PORT $SSH_USER@$SSH_HOST
    env_file:
      - .env
    expose:
      - "1337"
    network_mode: "host"
